name: Open a PR for a new release

on:
  workflow_dispatch:
    inputs:
      version:
        description: >-
          What version to release.
          Can be one of 'major', 'minor', 'patch', or a concrete version.
          See https://github.com/crate-ci/cargo-release/blob/7527065e413b9625ccb09800b765f6c49d011c79/docs/reference.md#bump-level for more details.
        required: true
        type: string

env:
  RUSTUP_TOOLCHAIN: stable

jobs:
  make-release-pr:
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: chainguard-dev/actions/setup-gitsign@main
      - name: Install cargo-release
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-release
      - name: Set up Rust cache
        uses: Swatinem/rust-cache@v2
      - uses: cargo-bins/release-pr@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ inputs.version }}
          crate-name: neo4j_testcontainers
